version: 2
jobs:
  build:
    docker:
      - image: gcc:latest

    working_directory: ~/source

    steps:
      - checkout

      - run:
          name: Install CMake
          command: |
            cd ..
            git clone https://gitlab.kitware.com/cmake/cmake.git
            cd cmake
            ./configure
            make

      - run:
          name: Run CMake
          command: |
            cd ..
            cd build
            ../cmake/cmake ../source

      - run:
          name: Compile
          command: |
            cd ..
            cd build
            make

      - run:
          name: Test
          command: |
            cd ..
            cd build
            make test
