version: 2
jobs:
  build:
    docker:
      - image: teeks99/clang-ubuntu:10

    working_directory: ~/source

    steps:
      - checkout

      - run:
          name: Install CMake
          command: |
            version=3.13
            build=3
            mkdir ~/temp
            cd ~/temp
            apt update
            apt install -y wget
            wget https://github.com/Kitware/CMake/releases/download/v3.13.3/cmake-3.13.3-Linux-x86_64.sh 
            mkdir /opt/cmake
            sh cmake-3.13.3-Linux-x86_64.sh --prefix=/opt/cmake --skip-license

      - run:
          name: Run CMake
          command: |
            cd ..
            mkdir build
            cd build
            CC=clang-10 CXX=clang++-10 /opt/cmake/bin/cmake -DCMAKE_BUILD_TYPE=Release ../source

      - run:
          name: Compile
          command: |
            cd ..
            cd build
            make -j2

      - run:
          name: Test Core
          command: |
            cd ..
            cd build
            /opt/cmake/bin/ctest -R minimum_core

      - run:
          name: Test Linear
          command: |
            cd ..
            cd build
            /opt/cmake/bin/ctest -R minimum_linear
