version: 2
jobs:
  build:
    docker:
      - image: gcc:latest

    working_directory: ~/source

    steps:
      - checkout

      - run:
          name: Install CMake
          command: |
            apt-get update
            apt-get install -y cmake

      - run:
          name: Run CMake
          command: |
            cd ..
            mkdir build
            cd build
            cmake ../source

      - run:
          name: Compile
          command: |
            cd ..
            cd build
            make

      - run:
          name: Test Core
          command: |
            cd ..
            cd build
            ctest -R minimum_core

      - run:
          name: Test Linear
          command: |
            cd ..
            cd build
            ctest -R minimum_linear
